### ISSUE TITLE
Differences with PEG.js

### ISSUE THREAD

**Issue by orefalo** [bitair-org/parser.js#1]
Hi,

nice project, thank you for sharing.

I was wondering if you could highlight the differences with PEG.js

Thank you

**Comment by beshan** [comment]
Hi. Thank you for your feedback. For some legal and technical reasons, we strictly avoid learning similar libraries while designing ours. The main goal of Parser.js is to provide a tool for meta-parsing (similar to meta-programming). An example can be defining a new operator like `|` for non-ordered choices.
